# -*- coding: utf-8 -*-
"""Untitled119.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ub4y6Pim5oFEVW-CPEjqxGAu6IjKkWFc
"""

!pip install transformers
!pip install torch
!pip install gradio

from transformers import pipeline

# Load the sentiment-analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

from transformers import pipeline
import gradio as gr

# Load the sentiment-analysis pipeline with a 3-class model
sentiment_pipeline = pipeline("sentiment-analysis", model="cardiffnlp/twitter-roberta-base-sentiment")

# Define the sentiment analysis function
def analyze_sentiment(text):
    result = sentiment_pipeline(text)[0]  # Get the first result

    # Mapping the string labels ('LABEL_0', 'LABEL_1', 'LABEL_2') to sentiment labels
    label_map = {'LABEL_0': "Negative", 'LABEL_1': "Neutral", 'LABEL_2': "Positive"}

    # Map the string label to sentiment label
    label = label_map.get(result['label'], "Unknown")  # Default to 'Unknown' if the label is not found
    score = result['score']  # Confidence score

    return f"Sentiment: {label}\nConfidence Score: {score:.2f}"

# Set up Gradio interface
iface = gr.Interface(fn=analyze_sentiment,
                     inputs="text",
                     outputs="text",
                     live=True,
                     title="Sentiment Analysis App",
                     description="Enter a sentence and get its sentiment analysis (Positive, Negative, or Neutral).")

# Launch the app
iface.launch()

